import type { EnemyShape } from './types';

export interface DungeonMonsterDef {
  ru: string;
  en: string;
  shape: EnemyShape;
  attackType: 'melee' | 'ranged' | 'charger';
}

// === DUNGEON MONSTERS (per dungeon, grouped by 4-wave blocks matching boss progression) ===
export const DUNGEON_MONSTERS: Record<string, DungeonMonsterDef[]> = {
  // ===== 1. ШЕПЧУЩАЯ ЧАЩА (Слизни, Орки, Огры, Эльфы, Циклопы) =====
  whispering_grove: [
    { ru: 'Зелёный слизень', en: 'Green Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Плюющийся слизень', en: 'Spitting Slime', shape: 'blob', attackType: 'ranged' },
    { ru: 'Кислотный слизень', en: 'Acid Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Шипастый летун', en: 'Spiked Flyer', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Болотная тина', en: 'Swamp Mire', shape: 'blob', attackType: 'melee' },
    { ru: 'Орк-разведчик', en: 'Orc Scout', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Дикий волк', en: 'Wild Wolf', shape: 'wolf', attackType: 'charger' },
    { ru: 'Хвойный кобольд', en: 'Pine Kobold', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Громила орков', en: 'Orc Brute', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Орочий шаман', en: 'Orc Shaman', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Боевой кабан', en: 'War Boar', shape: 'wolf', attackType: 'charger' },
    { ru: 'Лесной огр', en: 'Forest Ogre', shape: 'golem', attackType: 'melee' },
    { ru: 'Ловчая лоза', en: 'Snare Vine', shape: 'spider', attackType: 'ranged' },
    { ru: 'Огр-камнеметатель', en: 'Ogre Stonehrower', shape: 'golem', attackType: 'ranged' },
    { ru: 'Двуглавый огр', en: 'Two-Headed Ogre', shape: 'golem', attackType: 'melee' },
    { ru: 'Дикая гиена', en: 'Wild Hyena', shape: 'wolf', attackType: 'charger' },
    { ru: 'Болотный кадавр', en: 'Swamp Cadaver', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Тёмный эльф', en: 'Dark Elf', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Эльфийский лучник', en: 'Elven Archer', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Лесной леопард', en: 'Forest Leopard', shape: 'wolf', attackType: 'charger' },
    { ru: 'Эльф-маг', en: 'Elf Mage', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Страж дубравы', en: 'Grove Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Оживший корень', en: 'Animated Root', shape: 'spider', attackType: 'melee' },
    { ru: 'Циклоп-дитя', en: 'Cyclops Child', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Скальный грызун', en: 'Rock Gnawer', shape: 'wolf', attackType: 'charger' },
    { ru: 'Каменный прыгун', en: 'Stone Leaper', shape: 'beetle', attackType: 'melee' },
    { ru: 'Горный циклоп', en: 'Mountain Cyclops', shape: 'golem', attackType: 'melee' },
    { ru: 'Грозовой ворон', en: 'Storm Raven', shape: 'bat', attackType: 'ranged' },
    { ru: 'Живой булыжник', en: 'Living Boulder', shape: 'golem', attackType: 'melee' },
    { ru: 'Болотный слизень', en: 'Swamp Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Иловый ползун', en: 'Silt Crawler', shape: 'blob', attackType: 'melee' },
    { ru: 'Ядовитая жаба', en: 'Poison Toad', shape: 'blob', attackType: 'ranged' },
    { ru: 'Берсерк орков', en: 'Orc Berserker', shape: 'humanoid', attackType: 'charger' },
    { ru: 'Наездник на волке', en: 'Wolf Rider', shape: 'humanoid', attackType: 'charger' },
    { ru: 'Орочий барабанщик', en: 'Orc Drummer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Огр-людоед', en: 'Ogre Maneater', shape: 'golem', attackType: 'melee' },
    { ru: 'Цепной пёс', en: 'Chain Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Железный огр', en: 'Iron Ogre', shape: 'golem', attackType: 'melee' },
    { ru: 'Эльфийский копейщик', en: 'Elven Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Огненный сокол', en: 'Fire Falcon', shape: 'bat', attackType: 'ranged' },
    { ru: 'Страж заката', en: 'Sunset Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Старейший циклоп', en: 'Elder Cyclops', shape: 'golem', attackType: 'melee' },
    { ru: 'Рудный скорпион', en: 'Ore Scorpion', shape: 'spider', attackType: 'melee' },
    { ru: 'Скальный летун', en: 'Rock Flyer', shape: 'bat', attackType: 'ranged' },
    { ru: 'Королевский слизень', en: 'Royal Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Радужное желе', en: 'Rainbow Jelly', shape: 'blob', attackType: 'ranged' },
    { ru: 'Мутаген', en: 'Mutagen', shape: 'blob', attackType: 'melee' },
    { ru: 'Орочий чернокнижник', en: 'Orc Warlock', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Демонический пёс', en: 'Demonic Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Тёмный орк', en: 'Dark Orc', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Огр-титан', en: 'Ogre Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Лесной исполин', en: 'Forest Colossus', shape: 'golem', attackType: 'melee' },
    { ru: 'Оживший доспех огра', en: 'Animated Ogre Armor', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Высший эльф', en: 'High Elf', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Звездный леопард', en: 'Star Leopard', shape: 'wolf', attackType: 'charger' },
    { ru: 'Волшебный дракончик', en: 'Magic Drake', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Воин Трона', en: 'Throne Warrior', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Охранник Идола', en: 'Idol Guard', shape: 'golem', attackType: 'melee' },
    { ru: 'Древний голем леса', en: 'Ancient Forest Golem', shape: 'golem', attackType: 'melee' },
    { ru: 'Страж гнезда', en: 'Nest Guardian', shape: 'gargoyle', attackType: 'charger' },
  ],
  // ===== 2. ДРЕВНИЕ РУИНЫ ГНОМОВ =====
  gnomish_ruins: [
    { ru: 'Руинная крыса', en: 'Ruin Rat', shape: 'wolf', attackType: 'charger' },
    { ru: 'Гном-зомби', en: 'Gnome Zombie', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Шахтный паук', en: 'Mine Spider', shape: 'spider', attackType: 'melee' },
    { ru: 'Скелет-рудокоп', en: 'Skeleton Miner', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Пещерная летучая мышь', en: 'Cave Bat', shape: 'bat', attackType: 'ranged' },
    { ru: 'Огненный слизень', en: 'Fire Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Искровик', en: 'Sparkling', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Магма-жук', en: 'Magma Beetle', shape: 'beetle', attackType: 'melee' },
    { ru: 'Оживший доспех', en: 'Animated Armor', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Медный голем', en: 'Copper Golem', shape: 'golem', attackType: 'melee' },
    { ru: 'Ржавый страж', en: 'Rusty Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Каменная муха', en: 'Stone Fly', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Горгулья', en: 'Gargoyle', shape: 'gargoyle', attackType: 'charger' },
    { ru: 'Живой булыжник', en: 'Living Boulder', shape: 'golem', attackType: 'melee' },
    { ru: 'Осколочник', en: 'Shardling', shape: 'crystal', attackType: 'ranged' },
    { ru: 'Каменный червь', en: 'Stone Worm', shape: 'spider', attackType: 'melee' },
    { ru: 'Кристалл-скат', en: 'Crystal Ray', shape: 'crystal', attackType: 'ranged' },
    { ru: 'Подземный копатель', en: 'Underground Digger', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Гном-арбалетчик', en: 'Gnome Crossbowman', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Страж щита', en: 'Shield Guardian', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Гном-наёмник', en: 'Gnome Mercenary', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Железная гончая', en: 'Iron Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Механический паук', en: 'Mechanical Spider', shape: 'spider', attackType: 'melee' },
    { ru: 'Заводной летун', en: 'Clockwork Flyer', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Пылевой вихрь', en: 'Dust Whirlwind', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Песчаный прыгун', en: 'Sand Leaper', shape: 'beetle', attackType: 'melee' },
    { ru: 'Грозовой элементаль', en: 'Storm Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Древняя мумия', en: 'Ancient Mummy', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Терракотовый воин', en: 'Terracotta Warrior', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Проклятый жрец', en: 'Cursed Priest', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Рудный паразит', en: 'Ore Parasite', shape: 'beetle', attackType: 'melee' },
    { ru: 'Глубинный клещ', en: 'Deep Tick', shape: 'spider', attackType: 'melee' },
    { ru: 'Скальный грызун', en: 'Rock Gnawer', shape: 'wolf', attackType: 'charger' },
    { ru: 'Теневой копатель', en: 'Shadow Digger', shape: 'shadow', attackType: 'melee' },
    { ru: 'Взрывной плавун', en: 'Explosive Melter', shape: 'imp', attackType: 'charger' },
    { ru: 'Техно-дрон', en: 'Techno Drone', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Магматический краб', en: 'Magmatic Crab', shape: 'beetle', attackType: 'melee' },
    { ru: 'Лавовый шмель', en: 'Lava Bumblebee', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Базальтовый слизень', en: 'Basalt Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Темный сталкер', en: 'Dark Stalker', shape: 'shadow', attackType: 'charger' },
    { ru: 'Слепой безликий', en: 'Blind Faceless', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Плакальщик Бездны', en: 'Abyss Mourner', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Древний страж', en: 'Ancient Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Ожившая пила', en: 'Animated Saw', shape: 'humanoid', attackType: 'charger' },
    { ru: 'Рунический конструкт', en: 'Runic Construct', shape: 'golem', attackType: 'ranged' },
    { ru: 'Кристальный Скорпион', en: 'Crystal Scorpion', shape: 'spider', attackType: 'melee' },
    { ru: 'Алхимический летун', en: 'Alchemical Flyer', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Изумрудный скарабей', en: 'Emerald Scarab', shape: 'beetle', attackType: 'melee' },
    { ru: 'Рунный дух', en: 'Runic Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Страж Трона', en: 'Throne Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Алтарный голем', en: 'Altar Golem', shape: 'golem', attackType: 'melee' },
    { ru: 'Ожившая статуя', en: 'Animated Statue', shape: 'gargoyle', attackType: 'melee' },
    { ru: 'Гвардеец короля', en: 'Kings Guardsman', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Элитный стрелок', en: 'Elite Marksman', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Королевский маг', en: 'Royal Mage', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Вулканический слизень', en: 'Volcanic Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Проклятое золото', en: 'Cursed Gold', shape: 'crystal', attackType: 'ranged' },
    { ru: 'Ифрит', en: 'Ifrit', shape: 'imp', attackType: 'melee' },
    { ru: 'Личная гвардия короля', en: 'Royal Personal Guard', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Живой монолит', en: 'Living Monolith', shape: 'golem', attackType: 'melee' },
    { ru: 'Рунный титан', en: 'Runic Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Элитный паладин', en: 'Elite Paladin', shape: 'humanoid', attackType: 'ranged' },
  ],
  // ===== 3. НЕКРОПОЛЬ ЗЛА =====
  necropolis: [
    { ru: 'Скелет-воин', en: 'Skeleton Warrior', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Чумной гуль', en: 'Plague Ghoul', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Могильная крыса', en: 'Grave Rat', shape: 'wolf', attackType: 'charger' },
    { ru: 'Зомби в лохмотьях', en: 'Ragged Zombie', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Могильный червь', en: 'Grave Worm', shape: 'spider', attackType: 'melee' },
    { ru: 'Костяной пёс', en: 'Bone Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Призрак-плакальщик', en: 'Wailing Ghost', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Кровососущая летучая мышь', en: 'Vampire Bat', shape: 'bat', attackType: 'ranged' },
    { ru: 'Тень', en: 'Shadow', shape: 'shadow', attackType: 'melee' },
    { ru: 'Одержимый слуга', en: 'Possessed Servant', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Полтергейст', en: 'Poltergeist', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Призрак невесты', en: 'Bride Ghost', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Культист-фанатик', en: 'Cultist Fanatic', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Оскверненный пёс', en: 'Defiled Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Еретик-чернокнижник', en: 'Heretic Warlock', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Мутант из плоти', en: 'Flesh Mutant', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Кислотный слизень', en: 'Acid Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Чумная гончая', en: 'Plague Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Вампир-неофит', en: 'Vampire Neophyte', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Кровавая пиявка', en: 'Blood Leech', shape: 'spider', attackType: 'melee' },
    { ru: 'Ночной летун', en: 'Night Flier', shape: 'bat', attackType: 'ranged' },
    { ru: 'Гаргулья некрополя', en: 'Necropolis Gargoyle', shape: 'gargoyle', attackType: 'charger' },
    { ru: 'Теневой жнец', en: 'Shadow Reaper', shape: 'shadow', attackType: 'melee' },
    { ru: 'Высший вампир', en: 'High Vampire', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Ищейка крови', en: 'Blood Seeker', shape: 'wolf', attackType: 'charger' },
    { ru: 'Костяной копейщик', en: 'Bone Lancer', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Проклятая крыса', en: 'Cursed Rat', shape: 'wolf', attackType: 'charger' },
    { ru: 'Гниющий мертвец', en: 'Rotting Dead', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Мясной кадавр', en: 'Flesh Cadaver', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Токсичное облако', en: 'Toxic Cloud', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Сшитый ужас', en: 'Stitched Horror', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Привидение палача', en: 'Executioner Ghost', shape: 'spirit', attackType: 'melee' },
    { ru: 'Проклятые цепи', en: 'Cursed Chains', shape: 'shadow', attackType: 'melee' },
    { ru: 'Мучитель', en: 'Tormentor', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Дух склепа', en: 'Crypt Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Древнее привидение', en: 'Ancient Apparition', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Полуночная банши', en: 'Midnight Banshee', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Темный сектант', en: 'Dark Sectarian', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Вестник гибели', en: 'Harbinger of Doom', shape: 'shadow', attackType: 'ranged' },
    { ru: 'Призыватель костей', en: 'Bone Summoner', shape: 'skeleton', attackType: 'ranged' },
    { ru: 'Костяная гончая', en: 'Bone Hound', shape: 'skeleton', attackType: 'charger' },
    { ru: 'Проклятый лучник', en: 'Cursed Archer', shape: 'skeleton', attackType: 'ranged' },
    { ru: 'Костяной голем', en: 'Bone Golem', shape: 'golem', attackType: 'melee' },
    { ru: 'Костяной слуга Лича', en: 'Lich Bone Servant', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Ледяной призрак', en: 'Ice Phantom', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Морозный зомби', en: 'Frost Zombie', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Теневой летун', en: 'Shadow Flier', shape: 'bat', attackType: 'ranged' },
    { ru: 'Темный элементаль', en: 'Dark Elemental', shape: 'shadow', attackType: 'ranged' },
    { ru: 'Ищейка Бездны', en: 'Abyss Seeker', shape: 'wolf', attackType: 'charger' },
    { ru: 'Костяной дракончик', en: 'Bone Drake', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Смертоносный дух', en: 'Deadly Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Некро-скат', en: 'Necro Ray', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Элитный страж Лича', en: 'Lich Elite Guard', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Рыцарь смерти', en: 'Death Knight', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Проклятый всадник', en: 'Cursed Rider', shape: 'humanoid', attackType: 'charger' },
    { ru: 'Ледяной скелет', en: 'Ice Skeleton', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Замерзший зомби', en: 'Frozen Zombie', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Морозный призрак', en: 'Frost Phantom', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Высшая теневая стража', en: 'Supreme Shadow Guard', shape: 'shadow', attackType: 'melee' },
    { ru: 'Проклятый титан', en: 'Cursed Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Теневой паладин', en: 'Shadow Paladin', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Лич-ученик', en: 'Lich Apprentice', shape: 'skeleton', attackType: 'ranged' },
  ],
  // ===== 4. ДЖУНГЛИ ИДОЛ-КАРАВ =====
  idol_jungle: [
    { ru: 'Хищный цветок', en: 'Predatory Flower', shape: 'blob', attackType: 'melee' },
    { ru: 'Лесной леопард', en: 'Forest Leopard', shape: 'wolf', attackType: 'charger' },
    { ru: 'Плюющийся кобольд', en: 'Spitting Kobold', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Древесный кобольд', en: 'Wood Kobold', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Лозоплёт', en: 'Vine Weaver', shape: 'spider', attackType: 'ranged' },
    { ru: 'Дикая гиена', en: 'Wild Hyena', shape: 'wolf', attackType: 'charger' },
    { ru: 'Болотный слизень', en: 'Swamp Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Дикий крокодил', en: 'Wild Crocodile', shape: 'wolf', attackType: 'charger' },
    { ru: 'Топкий прыгун', en: 'Mire Leaper', shape: 'beetle', attackType: 'melee' },
    { ru: 'Жаба-переросток', en: 'Overgrown Toad', shape: 'blob', attackType: 'melee' },
    { ru: 'Кислотная тина', en: 'Acid Mire', shape: 'blob', attackType: 'ranged' },
    { ru: 'Иловый ползун', en: 'Silt Crawler', shape: 'blob', attackType: 'melee' },
    { ru: 'Дикая обезьяна', en: 'Wild Monkey', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Ядовитая оса', en: 'Poison Wasp', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Роевой жук', en: 'Swarm Beetle', shape: 'beetle', attackType: 'melee' },
    { ru: 'Ядовитая змея', en: 'Poison Snake', shape: 'spider', attackType: 'melee' },
    { ru: 'Лесной скорпион', en: 'Forest Scorpion', shape: 'spider', attackType: 'melee' },
    { ru: 'Плюющийся паук', en: 'Spitting Spider', shape: 'spider', attackType: 'ranged' },
    { ru: 'Дикарь-копейщик', en: 'Savage Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Маскирующийся охотник', en: 'Camouflaged Hunter', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Стрелок племени', en: 'Tribal Shooter', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Храмовый страж', en: 'Temple Guardian', shape: 'golem', attackType: 'melee' },
    { ru: 'Оживший тотем', en: 'Animated Totem', shape: 'golem', attackType: 'melee' },
    { ru: 'Проклятый идол', en: 'Cursed Idol', shape: 'golem', attackType: 'ranged' },
    { ru: 'Каменный ящер', en: 'Stone Lizard', shape: 'wolf', attackType: 'charger' },
    { ru: 'Ловчая лоза', en: 'Snare Vine', shape: 'spider', attackType: 'melee' },
    { ru: 'Плотоядный корень', en: 'Carnivorous Root', shape: 'spider', attackType: 'melee' },
    { ru: 'Болотный сектант', en: 'Swamp Sectarian', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Грязевик', en: 'Mud Being', shape: 'blob', attackType: 'melee' },
    { ru: 'Ил-элементаль', en: 'Silt Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Дикая горилла', en: 'Wild Gorilla', shape: 'golem', attackType: 'melee' },
    { ru: 'Обезьяна-копейщик', en: 'Monkey Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Павиан-переросток', en: 'Overgrown Baboon', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Обезьяна-шаман', en: 'Monkey Shaman', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Призрак джунглей', en: 'Jungle Phantom', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Древний дух воина', en: 'Ancient Warrior Spirit', shape: 'spirit', attackType: 'melee' },
    { ru: 'Ядовитый виверн', en: 'Poison Wyvern', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Огненная муха', en: 'Fire Fly', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Крылатый кобольд', en: 'Winged Kobold', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Теневая пантера', en: 'Shadow Panther', shape: 'wolf', attackType: 'charger' },
    { ru: 'Плюющийся лесной паук', en: 'Spitting Forest Spider', shape: 'spider', attackType: 'ranged' },
    { ru: 'Ищейка джунглей', en: 'Jungle Seeker', shape: 'wolf', attackType: 'charger' },
    { ru: 'Воин-ящер', en: 'Lizard Warrior', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Кентавр джунглей', en: 'Jungle Centaur', shape: 'humanoid', attackType: 'charger' },
    { ru: 'Элитный копейщик', en: 'Elite Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Древний тираннозавр', en: 'Ancient Tyrannosaurus', shape: 'dragon', attackType: 'melee' },
    { ru: 'Дикий раптор', en: 'Wild Raptor', shape: 'dragon', attackType: 'charger' },
    { ru: 'Птеродактиль', en: 'Pterodactyl', shape: 'bat', attackType: 'ranged' },
    { ru: 'Изумрудный элементаль', en: 'Emerald Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Живой мох', en: 'Living Moss', shape: 'blob', attackType: 'melee' },
    { ru: 'Болотный титан', en: 'Swamp Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Элитный копейщик Храма', en: 'Temple Elite Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Шаман крови', en: 'Blood Shaman', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Жрец Клыка', en: 'Fang Priest', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Крылатый змей', en: 'Winged Serpent', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Ядовитый дракончик', en: 'Poison Drake', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Летающая гадюка', en: 'Flying Viper', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Личная гвардия Кукулькана', en: 'Kukulkan Personal Guard', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Идол храма', en: 'Temple Idol', shape: 'golem', attackType: 'melee' },
    { ru: 'Верховный ящер', en: 'Supreme Lizard', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Змеиный страж', en: 'Serpent Guardian', shape: 'dragon', attackType: 'ranged' },
  ],
  // ===== 5. ЗАТОНУВШИЙ ФЛОТ =====
  sunken_fleet: [
    { ru: 'Одноногий матрос', en: 'One-Legged Sailor', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Пиратский пёс', en: 'Pirate Dog', shape: 'wolf', attackType: 'charger' },
    { ru: 'Стрелок мушкета', en: 'Musket Shooter', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Мертвый корсар', en: 'Dead Corsair', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Чайка-падальщик', en: 'Scavenger Gull', shape: 'bat', attackType: 'ranged' },
    { ru: 'Проклятый кок', en: 'Cursed Cook', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Сирена-искусительница', en: 'Temptress Siren', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Морская змея', en: 'Sea Serpent', shape: 'spider', attackType: 'melee' },
    { ru: 'Острый риф', en: 'Sharp Reef', shape: 'crystal', attackType: 'melee' },
    { ru: 'Кричащая русалка', en: 'Screaming Mermaid', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Водяной хлыст', en: 'Water Whip', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Коралловый летун', en: 'Coral Flyer', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Детеныш Кракена', en: 'Kraken Hatchling', shape: 'eye', attackType: 'melee' },
    { ru: 'Глубинный скат', en: 'Deep Ray', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Морской паук', en: 'Sea Spider', shape: 'spider', attackType: 'melee' },
    { ru: 'Малый кракен', en: 'Lesser Kraken', shape: 'eye', attackType: 'melee' },
    { ru: 'Элементаль волны', en: 'Wave Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Водоворот-живой', en: 'Living Maelstrom', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Мурлок-копейщик', en: 'Murloc Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Краб-щитоносец', en: 'Shield Crab', shape: 'beetle', attackType: 'melee' },
    { ru: 'Рыба-удильщик', en: 'Anglerfish', shape: 'eye', attackType: 'ranged' },
    { ru: 'Воин глубин', en: 'Deep Warrior', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Плюющаяся каракатица', en: 'Spitting Cuttlefish', shape: 'eye', attackType: 'ranged' },
    { ru: 'Океанский голем', en: 'Ocean Golem', shape: 'golem', attackType: 'melee' },
    { ru: 'Акула-людоед', en: 'Maneater Shark', shape: 'wolf', attackType: 'charger' },
    { ru: 'Пират-скелет', en: 'Skeleton Pirate', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Костяная рыба', en: 'Bone Fish', shape: 'skeleton', attackType: 'melee' },
    { ru: 'Утопленник в латах', en: 'Drowned in Armor', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Летучий призрак', en: 'Flying Ghost', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Тень каюты', en: 'Cabin Shadow', shape: 'shadow', attackType: 'melee' },
    { ru: 'Хищная сирена', en: 'Predatory Siren', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Морской угорь', en: 'Sea Eel', shape: 'spider', attackType: 'melee' },
    { ru: 'Штормовой клещ', en: 'Storm Tick', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Щупальце Бездны', en: 'Abyss Tentacle', shape: 'eye', attackType: 'melee' },
    { ru: 'Черный слизень моря', en: 'Black Sea Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Иглобрюх', en: 'Pufferfish', shape: 'eye', attackType: 'ranged' },
    { ru: 'Подводный охотник', en: 'Underwater Hunter', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Нага-колдун', en: 'Naga Warlock', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Черепаха-танк', en: 'Turtle Tank', shape: 'beetle', attackType: 'melee' },
    { ru: 'Командир флота', en: 'Fleet Commander', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Пушкарь-призрак', en: 'Ghost Gunner', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Мушкетер костей', en: 'Bone Musketeer', shape: 'skeleton', attackType: 'ranged' },
    { ru: 'Океанский дух', en: 'Ocean Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Сирена заката', en: 'Sunset Siren', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Волновая нага', en: 'Wave Naga', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Элитный кракен-воин', en: 'Elite Kraken Warrior', shape: 'eye', attackType: 'melee' },
    { ru: 'Рифовый ужас', en: 'Reef Horror', shape: 'eye', attackType: 'melee' },
    { ru: 'Элементаль цунами', en: 'Tsunami Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Императорская нага', en: 'Imperial Naga', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Морской дракончик', en: 'Sea Drake', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Акула-молот', en: 'Hammerhead Shark', shape: 'wolf', attackType: 'charger' },
    { ru: 'Проклятый адмирал', en: 'Cursed Admiral', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Фантомный корабль', en: 'Phantom Ship', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Теневой матрос', en: 'Shadow Sailor', shape: 'shadow', attackType: 'melee' },
    { ru: 'Страж Трезубца', en: 'Trident Guardian', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Водный гигант', en: 'Water Giant', shape: 'golem', attackType: 'melee' },
    { ru: 'Титан волн', en: 'Titan of Waves', shape: 'golem', attackType: 'melee' },
    { ru: 'Гвардия Бездны', en: 'Abyss Guard', shape: 'eye', attackType: 'melee' },
    { ru: 'Коралловый титан', en: 'Coral Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Глубинный дракон', en: 'Deep Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Океанский ужас', en: 'Ocean Horror', shape: 'eye', attackType: 'melee' },
  ],
  // ===== 6. НЕБЕСНАЯ ЦИТАДЕЛЬ =====
  sky_citadel: [
    { ru: 'Белый грифон', en: 'White Gryphon', shape: 'gargoyle', attackType: 'melee' },
    { ru: 'Облачный прыгун', en: 'Cloud Leaper', shape: 'beetle', attackType: 'melee' },
    { ru: 'Птица-рух', en: 'Roc Bird', shape: 'bat', attackType: 'charger' },
    { ru: 'Бронированный грифон', en: 'Armored Gryphon', shape: 'gargoyle', attackType: 'melee' },
    { ru: 'Молниеносный орел', en: 'Lightning Eagle', shape: 'bat', attackType: 'ranged' },
    { ru: 'Пернатый волк', en: 'Feathered Wolf', shape: 'wolf', attackType: 'charger' },
    { ru: 'Падший ангел', en: 'Fallen Angel', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Теневой летун', en: 'Shadow Flier', shape: 'shadow', attackType: 'ranged' },
    { ru: 'Порождение тучи', en: 'Stormcloud Spawn', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Серафим-копейщик', en: 'Seraph Lancer', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Световой элементаль', en: 'Light Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Ожившая статуя', en: 'Animated Statue', shape: 'gargoyle', attackType: 'melee' },
    { ru: 'Малый бес', en: 'Lesser Imp', shape: 'imp', attackType: 'melee' },
    { ru: 'Огненная гончая', en: 'Fire Hound', shape: 'wolf', attackType: 'charger' },
    { ru: 'Огненный летун', en: 'Fire Flier', shape: 'bat', attackType: 'ranged' },
    { ru: 'Рогатый демон', en: 'Horned Demon', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Огненный чернокнижник', en: 'Fire Warlock', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Суккуб', en: 'Succubus', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Небесный дракончик', en: 'Sky Drake', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Синий виверн', en: 'Blue Wyvern', shape: 'dragon', attackType: 'charger' },
    { ru: 'Искровой ящер', en: 'Spark Lizard', shape: 'dragon', attackType: 'melee' },
    { ru: 'Штормовой дракон', en: 'Storm Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Грозовая гарпия', en: 'Storm Harpy', shape: 'gargoyle', attackType: 'ranged' },
    { ru: 'Облачный скат', en: 'Cloud Ray', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Крылатый бес', en: 'Winged Imp', shape: 'imp', attackType: 'melee' },
    { ru: 'Горящий слизень', en: 'Burning Slime', shape: 'blob', attackType: 'melee' },
    { ru: 'Ифрит цитадели', en: 'Citadel Ifrit', shape: 'imp', attackType: 'melee' },
    { ru: 'Ангел карающий', en: 'Punishing Angel', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Меч правосудия', en: 'Sword of Justice', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Святой дух', en: 'Holy Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Грозовой грифон', en: 'Thunder Gryphon', shape: 'gargoyle', attackType: 'charger' },
    { ru: 'Элементаль воздуха', en: 'Air Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Воздушная нимфа', en: 'Air Nymph', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Демон Бездны', en: 'Abyss Demon', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Теневой прыгун', en: 'Shadow Leaper', shape: 'shadow', attackType: 'charger' },
    { ru: 'Тёмный горгулья', en: 'Dark Gargoyle', shape: 'gargoyle', attackType: 'melee' },
    { ru: 'Изумрудный дракон', en: 'Emerald Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Небесный леопард', en: 'Sky Leopard', shape: 'wolf', attackType: 'charger' },
    { ru: 'Звездный летун', en: 'Star Flier', shape: 'beetle', attackType: 'ranged' },
    { ru: 'Каратель небес', en: 'Sky Punisher', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Золотой рыцарь', en: 'Golden Knight', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Лучеметчик', en: 'Ray Thrower', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Огненный бес-гвардеец', en: 'Fire Imp Guard', shape: 'imp', attackType: 'melee' },
    { ru: 'Палач Преисподней', en: 'Infernal Executioner', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Ифрит-маг', en: 'Ifrit Mage', shape: 'imp', attackType: 'ranged' },
    { ru: 'Черный виверн', en: 'Black Wyvern', shape: 'dragon', attackType: 'charger' },
    { ru: 'Дракон пустоты', en: 'Void Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Ищейка тени', en: 'Shadow Seeker', shape: 'shadow', attackType: 'charger' },
    { ru: 'Звездный ангел', en: 'Star Angel', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Космический феникс', en: 'Cosmic Phoenix', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Дух кометы', en: 'Comet Spirit', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Демон-титан', en: 'Demon Titan', shape: 'golem', attackType: 'melee' },
    { ru: 'Огненный исполин', en: 'Fire Colossus', shape: 'golem', attackType: 'melee' },
    { ru: 'Властелин преисподней', en: 'Underworld Overlord', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Древний золотой дракон', en: 'Ancient Golden Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Солнечный элементаль', en: 'Solar Elemental', shape: 'spirit', attackType: 'ranged' },
    { ru: 'Высшая гарпия', en: 'Supreme Harpy', shape: 'gargoyle', attackType: 'ranged' },
    { ru: 'Небесный паладин', en: 'Sky Paladin', shape: 'humanoid', attackType: 'melee' },
    { ru: 'Элитный серафим', en: 'Elite Seraph', shape: 'humanoid', attackType: 'ranged' },
    { ru: 'Дракон вечности', en: 'Eternal Dragon', shape: 'dragon', attackType: 'ranged' },
    { ru: 'Дух небес', en: 'Sky Spirit', shape: 'spirit', attackType: 'ranged' },
  ],
};